Entity/Commit.php
<?php

namespace Musicjerm\Bundle\JermBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="git_commit")
 * @ORM\Entity(repositoryClass="Musicjerm\Bundle\JermBundle\Repository\CommitRepository")
 */
class Commit
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=128)
     */
    private $gitRepo;

    /**
     * @var string
     * @ORM\Column(type="string", length=128)
     */
    private $commit;

    /**
     * @var string
     * @ORM\Column(type="string", length=128)
     */
    private $author;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $notes;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    public function setGitRepo($gitRepo)
    {
        $this->gitRepo = $gitRepo;
        return $this;
    }

    public function getGitRepo(): string
    {
        return $this->gitRepo;
    }

    public function setCommit($commit)
    {
        $this->commit = $commit;
        return $this;
    }

    public function getCommit(): string
    {
        return $this->commit;
    }

    public function getShortCommit(): string
    {
        return substr($this->commit, 0, 7);
    }

    public function setAuthor($author)
    {
        $this->author = $author;
        return $this;
    }

    public function getAuthor(): string
    {
        return $this->author;
    }

    public function setNotes($notes)
    {
        $this->notes = $notes;
        return $this;
    }

    public function getNotes(): string
    {
        return $this->notes;
    }

    public function setDate($date)
    {
        $this->date = $date;
        return $this;
    }

    public function getDate(): \DateTime
    {
        return $this->date;
    }

    public function getDateString(): string
    {
        return $this->getDate()->format('Y-m-d h:i a');
    }
}

Resources/views/Modal/app_config_form.html.twig
{% extends '@JermBundle/Modal/form.html.twig' %}

{% block form %}
    {{ parent() }}

    <a id="magic_url_btn" class="btn btn-sm btn-link">
        <i class="fa fa-magic"></i>
        Click here to set URL from application parameters
    </a>
{% endblock %}

Resources/views/Modal/batch_subscriber.html.twig
{% extends '@JermBundle/Modal/form.html.twig' %}

{% block form %}
    {{ parent() }}
    <div class="callout callout-warning">Subscribers will be created for the following line(s).</div>
    <div class="table-responsive">
        <table class="table table-condensed">
            <tbody>
            {% for line in entity_lines %}
                <tr>
                    <td class="text-muted">{{ loop.index }}</td>
                    <td>{{ line }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

Resources/views/Modal/blank.html.twig
{% if modal_size is not defined %}{% set modal_size = '' %}{% endif %}
<div class="modal-dialog {{ modal_size }}">
    <div class="modal-content box">

        {% block content %}
            <div class="modal-body">
                <div class="alert alert-info">
                    <i class="fa fa-exclamation-triangle"></i>
                    This is an empty modal template.  You should consider extending and replacing the content block.
                </div>
            </div>
        {% endblock %}

        <div id="action_loading_div" class="overlay">
            <i class="fa fa-spinner fa-pulse text-gray"></i>
        </div>

    </div>
</div>

<script src="{{ asset('bundles/jerm/js/hideActionSpinner.js') }}"></script>
{% block javascripts %}{% endblock %}

Resources/views/Modal/delete_form.html.twig
{% extends '@JermBundle/Modal/form.html.twig' %}

{% block form %}
    <pre><i class="fa fa-warning"></i> Warning, this cannot be undone.  Unchecked items may not be deleted.</pre>

    <div class="table-responsive">
        <table class="table">
            <tbody>
            {% for key, item in delete_array %}
                {% if item.delete %}
                    <tr>
                        <td><i class="fa fa-check-square-o"></i></td>
                        <td>{{ key }}</td>
                        <td>{{ item.string }}</td>
                    </tr>
                {% else %}
                    <tr class="text-muted">
                        <td><i class="fa fa-square-o"></i></td>
                        <td>{{ key }}</td>
                        <td>{{ item.string }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>

    {{ parent() }}
    {% if delete_count > 0 %}
        <div><i class="fa fa-warning"></i> {{ delete_count }} item(s) will be deleted.</div>
    {% else %}
        <div><i class="fa fa-warning"></i> No items to delete.</div>
    {% endif %}
{% endblock %}

{% block footer %}
    <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
    {% if delete_count > 0 %}
        <input id="action_submit_btn" type="submit" value="Confirm" class="btn btn-danger btn-flat pull-right">
    {% else %}
        <input id="action_submit_btn" type="submit" value="Confirm" class="btn btn-danger btn-flat pull-right" disabled>
    {% endif %}
{% endblock %}

Resources/views/Modal/doctrine_check_notification.html.twig
{% extends '@JermBundle/Modal/blank.html.twig' %}

{% block content %}
    <div class="modal-body">

        <h4><i class="fa fa-database"></i> Doctrine Updater</h4>
        {% if type is defined and type == 'success' %}
            <p class="text-info">
                {{ message|nl2br }}
            </p>
        {% elseif type is defined and type == 'error' %}
            <p class="text-red">
                <i class="fa fa-ban"></i>
                {{ message|nl2br }}
            </p>
        {% endif %}

    </div>

    <div class="modal-footer">

        <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>

        {% if not migrate %}
            <a class="btn btn-sm btn-flat btn-info modal_redirect"
               data-href="{{ path('jerm_bundle_app_doctrine_update', { 'method': 'force' }) }}">
                <i class="fa fa-refresh"></i> Migrate Changes
            </a>
        {% endif %}

    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(function () {
            let loadSpinner = $('#action_loading_div');
            let actionModal = $('#action_modal');
            let modalRedirect = $('.modal_redirect');

            modalRedirect.on('click', function(){
                $.ajax({
                    type: 'GET',
                    url: $(this).attr('data-href'),
                    success: function(data){
                        actionModal.html(data)
                    },
                    error: function(xhr){
                        alert('Something has broken. Error: '+xhr.status)
                    }
                });
                loadSpinner.show();
            });
        })
    </script>
{% endblock %}

Resources/views/Modal/dt_config_form.html.twig
{% extends '@JermBundle/Modal/form.html.twig' %}

{% block form %}
    <div class="row">
        <div class="col-xs-12 col-md-8">
            {{ form_row(form.name) }}
        </div>
        <div class="col-xs-12 col-md-4">
            <strong>Set as Primary</strong>
            {{ form_row(form.isPrimary) }}
        </div>
    </div>
    {% form_theme form _self %}
    <div class="text-red">
        {{ form_errors(form.view) }}
        {{ form_errors(form.dataDump) }}
    </div>
    <div class="table-responsive">
        <table id="dt_config_table" class="table table-condensed">
            <thead>
            <tr>
                <th></th>
                <th>
                    <input id="select_all_view" type="checkbox" title="select_all_view"> View
                </th>
                <th>
                    <input id="select_all_csv" type="checkbox" title="select_all_csv"> CSV
                </th>
                <th>Column</th>
                <th>Tooltip</th>
                <th>
                    <a class="btn btn-link btn-sm modal_redirect" data-href="{{ resetUrl }}"><i class="fa fa-undo fa-lg"></i></a>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for key in colOrder %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ form_row(attribute(form.view, key), { 'attr': { 'class': 'view_selector' } }) }}</td>
                    <td>{{ form_widget(attribute(form.dataDump, key), { 'attr': { 'class': 'csv_selector' } }) }}</td>
                    <td>
                        {{ attribute(columnNames, key) }}
                        {{ form_widget(attribute(form.colOrder, key)) }}
                    </td>
                    <td>{{ form_widget(attribute(form.tooltip, key)) }}</td>
                    <td class="sortHandle">
                        <i class="fa fa-th fa-2x fa-rotate-90 text-info"></i>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-xs-6">
            {{ form_row(form.sortId) }}
        </div>
        <div class="col-xs-6">
            {{ form_row(form.sortDir) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('libraries/jQuery-UI/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('libraries/jQuery-UI-Touch-Punch/jquery.ui.touch-punch.min.js') }}"></script>
    <script src="{{ asset('bundles/jerm/js/dtConfigForm.js') }}"></script>
{% endblock %}

Resources/views/Modal/form.html.twig
{% extends '@JermBundle/Modal/blank.html.twig' %}

{% form_theme form '@JermBundle/Form/bootstrap_extended_layout.html.twig' %}

{% block content %}
    {{ form_start(form, { 'attr': { 'id': 'action_form' } }) }}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        {% block header %}{% if header is defined %}<h4 class="modal-title">{{ header }}</h4>{% endif %}{% endblock %}
    </div>

    <div class="modal-body">
        {% block form %}{{ form_widget(form) }}{% endblock %}
    </div>

    <div class="modal-footer">
        {% block footer %}
            {% if previous_path is defined and previous_path %}
                <button type="button" class="btn btn-default btn-flat pull-left modal_redirect" data-href="{{ previous_path }}">Back</button>
            {% else %}
                <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
            {% endif %}
            <input id="action_submit_btn" type="submit" value="Confirm" class="btn btn-primary btn-flat pull-right">
        {% endblock %}
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/jerm/js/modalForm.js') }}"></script>
    {% if front_load is defined %}
        {% for js_file in front_load %}
            <script src="{{ asset(js_file) }}"></script>
        {% endfor %}
    {% endif %}
{% endblock %}

Resources/views/Modal/import_form.html.twig
{% extends '@JermBundle/Modal/form.html.twig' %}

{% block headers %}
    Upload data for import ({{ entity }} Entity)
{% endblock %}

{% block form %}
    {{ parent() }}
    {% if truncate %}
        <div class="callout callout-danger">
            Existing data will be removed on upload.
        </div>
    {% else %}
        <div class="callout callout-warning">
            Existing items will be updated.  New items will be added.
        </div>
    {% endif %}
    <p class="text text-info">
        Please make sure your data contains the following columns:
    </p>
    <table class="table table-condensed">
        <thead>
        <tr>
            <th></th>
            <th>Column</th>
            <th>Type</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for key,val in structure %}
            <tr>
                <td class="text-muted">{{ loop.index }}</td>
                <td>{{ val.name }}</td>
                <td>
                    {{ val.type }}
                    {% if val.foreignKey %}
                        ({{ val.foreignKey.table }}.{{ val.foreignKey.column }})
                    {% elseif val.length %}
                        ({{ val.length }})
                    {% endif %}
                </td>
                <td class="text-orange">{% if val.primary == true %}<i class="fa fa-key"></i> Key{% endif %}</td>
                <td class="text-maroon">{% if val.unique == true %}<i class="fa fa-file-text"></i> Unique{% endif %}</td>
                <td class="text-blue">{% if val.required %}<i class="fa fa-asterisk"></i> Required{% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-link" href="{{ path('jerm_bundle_importer_get_template', { 'entity': entity }) }}">Download Template</a>
{% endblock %}

Resources/views/Modal/notification.html.twig
{% extends '@JermBundle/Modal/blank.html.twig' %}

{% block content %}

    <div class="modal-body">

        {% if type is defined and type == 'success' %}
            <p class="text-green">
                <i class="fa fa-check-circle"></i>
                {{ message|nl2br }}
            </p>
        {% elseif type is defined and type == 'warning' %}
            <p class="text-orange">
                <i class="fa fa-exclamation-triangle"></i>
                {{ message|nl2br }}
            </p>
        {% elseif type is defined and type == 'error' %}
            <p class="text-red">
                <i class="fa fa-ban"></i>
                {{ message|nl2br }}
            </p>
        {% else %}
            <p class="text-light-blue">
                <i class="fa fa-info-circle"></i>
                {{ message|nl2br }}
            </p>
        {% endif %}

        {% if href_link is defined %}
            <a href="{{ href_link }}" class="btn btn-link">
                {% if href_title is defined %}{{ href_title }}{% else %}{{ href_link }}{% endif %}
            </a>
        {% endif %}

    </div>

    {% if fade is not defined or not fade %}
        <div class="modal-footer">
            <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
        </div>
    {% endif %}

{% endblock %}

{% block javascripts %}
    <script id="notification_script"
        src="{{ asset('bundles/jerm/js/modalNotification.js') }}"
            {% if full_refresh is defined and full_refresh %}
                data-full-refresh="true"
            {% endif %}
            {% if refresh is defined and refresh %}
                data-refresh="true"
            {% endif %}
            {% if clear_session is defined and clear_session %}
                data-clear="true"
            {% endif %}
            {% if fade is defined and fade %}
                data-fade="true"
            {% endif %}
    ></script>
{% endblock %}

Resources/views/Modal/notification_view.html.twig
{% extends '@JermBundle/Modal/blank.html.twig' %}

{% block content %}

    <div class="modal-header">
        <button class="close" type="button" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
            {% if notification.icon %}
                <i class="fa fa-{{ notification.icon }}"></i>
            {% endif %}
            {{ notification.subject }}
        </h4>
        <small class="text-muted">{{ notification.dateString }}</small>
    </div>

    <div class="modal-body">

        {% if notification.class %}
            <p class="text-{{ notification.class }}">
                {{ notification.message|nl2br }}
            </p>
        {% else %}
            <p class="text-info">
                {{ notification.message|nl2br }}
            </p>
        {% endif %}

    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default btn-flat pull-left" data-dismiss="modal">Close</button>
    </div>

{% endblock %}

{% block javascripts %}
    <script
            id="notification_script"
            src="{{ asset('bundles/jerm/js/modalNotificationView.js') }}"
            data-status="{{ notification_status }}"
            data-message="{{ notification.id }}"
    >
    </script>
{% endblock %}